### ISSUE TITLE
Búsqueda de Administradores incompleta

### ISSUE THREAD

**Issue by jorgeis** [jorgeis/PuertasCIT#8]
En el formulario de búsqueda de administradores, el autoacompletado funciona bien, pero si se escribe algo y se pulsa en buscar, siempre dice que el Administrador no ha sido encontrado, a pesar de que si existen coincidencias con el dato ingresado.

**Comment by jorgeis** [comment]
Imagino que quizá solo hay que quitar el botón de buscar...

**Comment by abrahamramirez** [comment]
Correigo en #9

**Comment by jorgeis** [comment]
Con la corrección #9 aún si se hace una búsqueda como 'Juan Perez', que incluye nombre y un apellido no realiza la consulta. En 9dd31416fa103ce891e3a4f7b9a75bd11c7312fd se propone una solución con consultas nativas, ya implementada en la búsqueda de clientes.

**Comment by jorgeis** [comment]
Corregido en b9ca45141a65ad2624f137851bf4db226cfbc9d5
